### ISSUE TITLE
allow node 16

### ISSUE THREAD

**Issue by OleksiiKachan** [NoriSte/cypress-wait-until#472]
https://github.com/NoriSte/cypress-wait-until/blob/0a1545b71686900543e634901b0a0a43723cdad3/package.json#L7

please allow node 16. not everybody can bump to 18 yet. 16 has good half a year at least yet

**Comment by knorrium** [comment]
@OleksiiKachan thanks for raising this.

It took me a while to realize this was causing my Github Action to fail due to webpack compilation errors. My action was set to run on Node v16 - after updating it to v18, the tests ran fine again.

@NoriSte I think this should have been called out in the release notes as part of the breaking changes.

**Comment by NoriSte** [comment]
Sure, that's my bad! I hope to find the span to fix it quickly.

**Comment by NoriSte** [comment]
all-contributors please add @OleksiiKachan for bug

**Comment by NoriSte** [comment]
@all-contributors please add @OleksiiKachan for bug

**Comment by NoriSte** [comment]
- I updated [the v2.0.0 release](https://github.com/NoriSte/cypress-wait-until/releases/tag/v2.0.0)
- I merged @knorrium's PR
- I released [v2.0.1](https://github.com/NoriSte/cypress-wait-until/releases/tag/v2.0.1)

Let me know if it works, thank you all and sorry ❤️
